[package]
name = "xkk-gate"
version.workspace = true
edition.workspace = true

[dependencies]
xkk-app.workspace = true
prost.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
xkk-cache.workspace = true
xkk-common.workspace = true
xkk-config.workspace = true
xkk-persist.workspace = true
xkk-protocol.workspace = true
xframe.workspace = true
xredis.workspace = true
xtoken = { path = "../../../deps-rust/xtoken" }
xutil.workspace = true
