[package]
name = "xkk-robot"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
prost.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
xkk-config.workspace = true
xkk-protocol.workspace = true
xnet.workspace = true
xproto.workspace = true
