[package]
name = "xkk-protocol"
version.workspace = true
edition.workspace = true
build = "build.rs"

[dependencies]
prost.workspace = true
serde.workspace = true
thiserror.workspace = true
xproto.workspace = true
xmongo.workspace = true

[build-dependencies]
prost.workspace = true
prost-build.workspace = true
prost-types.workspace = true
protoc-bin-vendored.workspace = true
protoc-gen-xmongo-trait.workspace = true
xproto = { workspace = true, features = ["codegen"] }
