[package]
name = "xkk-auth"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
xfastid.workspace = true
xframe.workspace = true
xkk-cache.workspace = true
xkk-common.workspace = true
xkk-config.workspace = true
xkk-persist.workspace = true
xkk-protocol.workspace = true
xlog.workspace = true
xmongo.workspace = true
xredis.workspace = true
xtoken = { path = "../../../deps-rust/xtoken" }
xutil.workspace = true
