[package]
name = "xkk-query"
version.workspace = true
edition.workspace = true

[dependencies]
xkk-app.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
xkk-common.workspace = true
xkk-config.workspace = true
xkk-persist.workspace = true
xkk-protocol.workspace = true
xframe.workspace = true
