[package]
name = "xkk-public"
version.workspace = true
edition.workspace = true

[dependencies]
dashmap.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
xkk-cache.workspace = true
xkk-common.workspace = true
xkk-config.workspace = true
xkk-persist.workspace = true
xkk-protocol.workspace = true
xframe.workspace = true
xlog.workspace = true
xlru.workspace = true
