syntax = "proto3";

package xkk.v1;

import "xkk.proto";

//@rust_bson_trait account
message AccountData {
  string account = 1; // @inject_tag: bson:"_id"
  string credential_hash = 2; // @inject_tag: bson:"cred"
  repeated Role roles = 3; // @inject_tag: bson:"roles,omitempty"
  int64 created_at = 4; // @inject_tag: bson:"ct"
}

//@rust_bson_trait player
message PlayerData {
  int64 gid = 1; // @inject_tag: bson:"_id"
  PlayerInfo profile = 2; // @inject_tag: bson:"profile"
  map<int32, int64> items = 3; // @inject_tag: bson:"items,omitempty"
}

//@rust_bson_trait public_player
message PublicPlayerData {
  int64 gid = 1; // @inject_tag: bson:"_id"
  MailData mail = 2; // @inject_tag: bson:"mail"
}

message MailData {
  reserved 1;
  repeated Mail mails = 2; // @inject_tag: bson:"mails,omitempty"
}
